project:
  type: website
  output-dir: docs

website:
  title: "Hoang Son Lai - Data Analyst"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/yourusername
      - icon: linkedin
        href: https://linkedin.com/in/yourprofile
      - icon: envelope
        href: mailto:hlai0022@student.monash.edu

format:
  html:
    theme: lumen
    css: styles.css


