project:
  type: website
  output-dir: docs

website:
  title: "Hoang Son's Data Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/laihoangson
      - icon: linkedin
        href: https://linkedin.com/in/hoang-son-lai-92ab19282
      - icon: envelope
        href: mailto:hlai0022@student.monash.edu

format:
  html:
    theme: flatly
    css: styles.css


